[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["cd frontend && npm ci --no-optional --cache /tmp/.npm && npm run build"]

[start]
cmd = "cd frontend && npm start"