[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm ci && npm run build"

[deploy]
startCommand = "cd frontend && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"